<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Gfn.Cli</RootNamespace>
    <AssemblyName>gfn</AssemblyName>
    <Description>Command line driver for the Good for Nothing compiler.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gfn.Compiler\Gfn.Compiler.csproj" />
  </ItemGroup>

</Project>
